AllCops:
  TargetRubyVersion: 2.3.7
  TargetRailsVersion: 4.2.11

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FormatStringToken:
  EnforcedStyle: template

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false
